server:
  port: 1234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: coupon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultzone: http://localhost:8761/eureka
